# Generated by Django 5.0.2 on 2024-02-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_remove_comment_reply_remove_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
