# Generated by Django 5.0.2 on 2024-02-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_remove_historicalpost_likes_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
